// Website Routes
export const coursesUrl = '/courses'
export const cartUrl = '/cart'
export const wishlitUrl = '/wishlist'
export const thankYouUrl = '/thank-you'
export const privacyPolicyUrl = '/privacy-policy'
export const termsAndConditionsUrl = '/terms-and-conditions'
export const refundPolicyUrl = '/refund-policy'
export const faq = '/faq'
export const aboutUsUrl = '/about-us'
export const categoryUrl = '/category'
export const blogUrl = '/blog'
export const contactUsUrl = '/contact-us'

// Student Routes
export const studentDashboardUrl = '/learners/dashboard'
export const myCoursesUrl = '/learners/my-courses'
export const courseContentUrl = '/learners/course/content'
export const courseDetailUrl = '/learners/course/details'
export const studentProfileUrl = '/learners/profile'
export const studentPaymentsUrl = '/learners/payments'
export const studentNotesUrl = '/learners/notes'
export const studentReviewsUrl = '/learners/reviews'
export const studentCertificatesUrl = '/learners/certificates'

// Admin Routes
export const adminDashboardUrl = '/admin/dashboard'
export const adminCoursesUrl = '/admin/courses'
export const courseModules = '/admin/course-modules'
export const editCourseUrl = '/admin/courses/edit'
export const adminCourseCategoryUrl = '/admin/categories'
export const earningsUrl = '/admin/earnings'
export const adminStudentsUrl = '/admin/students'
export const adminReviewssUrl = '/admin/reviews'
export const adminAnalyticsUrl = '/admin/analytics'
export const adminCouponsUrl = '/admin/coupons'
export const adminBlogUrl = '/admin/blog'
export const moduleComponentUrl = '/admin/module-components'
export const componentPreviewUrl = '/admin/courses/component/preview'
export const courseStudentsUrl = '/admin/courses/students'

// Authentication Routes
export const loginUrl = '/sign-in'
export const forgotPasswordUrl = '/forgot-password'
export const changePasswordUrl = '/change-password'
export const registerUrl = '/sign-up'